export const Path = {
  ROOT: '/',
  LOGIN: '/auth/login',
  LOGGED: '/auth/logged',
  LOGOUT: '/auth/logout',
  DASHBOARD: '/dashboard',
  LIST_TO_WATCH: '/dashboard/to-watch',
  ITEM_TO_WATCH: (id: string) => `/dashboard/to-watch/${id}`,
  LIST_WATCHED: '/dashboard/watched',
  ITEM_WATCHED: (id: string) => `/dashboard/watched/${id}`,
  SEARCH: '/dashboard/search',
  SETTINGS: '/dashboard/settings',
  SEARCH_PARAM: (query: string) => `/dashboard/search?query=${query}`,
  SEARCH_RESULT: (id: string = ':id') => `/dashboard/search/${id}`,
  FEATURES: '/dashboard/features',
};
